In [1]:
""" ACTIVE JUPYTER NOTEBOOK TO BATCH RUN UNIT MATCHING ALGORITHM """

' ACTIVE JUPYTER NOTEBOOK TO BATCH RUN UNIT MATCHING ALGORITHM '

In [2]:
# Outside imports
import os, sys
import numpy as np
import matplotlib.pyplot as plt

# Set necessary paths / make project path = ...../neuroscikit/
unit_matcher_path = os.getcwd()
prototype_path = os.path.abspath(os.path.join(unit_matcher_path, os.pardir))
project_path = os.path.abspath(os.path.join(prototype_path, os.pardir))
lab_path = os.path.abspath(os.path.join(project_path, os.pardir))
sys.path.append(project_path)
os.chdir(project_path)
print(project_path)

# Internal imports

# Read write modules
from x_io.rw.axona.batch_read import make_study
from _prototypes.unit_matcher.read_axona import read_sequential_sessions, temp_read_cut
from _prototypes.unit_matcher.write_axona import format_new_cut_file_name

# Unit matching modules
from _prototypes.unit_matcher.main import format_cut, run_unit_matcher, map_unit_matches_first_session, map_unit_matches_sequential_session
from _prototypes.unit_matcher.session import compare_sessions
from _prototypes.unit_matcher.waveform import time_index, derivative, derivative2, morphological_points

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\neuroscikit


In [3]:
""" ONLY EDIT THE SETTINGS IN THIS NEXT CELL """

' ONLY EDIT THE SETTINGS IN THIS NEXT CELL '

In [4]:
""" If a setting is not used for your analysis (e.g. smoothing_factor), just pass in an arbitrary value or pass in 'None' """
STUDY_SETTINGS = {

    'ppm': 511,  # EDIT HERE

    'smoothing_factor': None, # EDIT HERE

    'useMatchedCut': False,  # EDIT HERE, set to False if you want to use runUnitMatcher, set to True after to load in matched.cut file
}


# Switch devices to True/False based on what is being used (to be extended for more devices in future)
device_settings = {'axona_led_tracker': True, 'implant': True} 

# Make sure implant metadata is correct, change if not, AT THE MINIMUM leave implant_type: tetrode
implant_settings = {'implant_type': 'tetrode', 'implant_geometry': 'square', 'wire_length': 25, 'wire_length_units': 'um', 'implant_units': 'uV'}

# WE ASSUME DEVICE AND IMPLANT SETTINGS ARE CONSISTENCE ACROSS SESSIONS, IF THIS IS NOT THE CASE PLEASE LET ME KNOW

# Set channel count + add device/implant settings
SESSION_SETTINGS = {
    'channel_count': 4, # EDIT HERE, default is 4, you can change to other number but code will check how many tetrode files are present and set that to channel copunt regardless
    'devices': device_settings, # EDIT HERE
    'implant': implant_settings, # EDIT HERE
}

STUDY_SETTINGS['session'] = SESSION_SETTINGS

settings_dict = STUDY_SETTINGS

In [10]:
data_dir = lab_path + r'\neuroscikit_test_data\single_sequential'

# To use in unit matching
settings_dict_unmatched = settings_dict
settings_dict_unmatched['useMatchedCut'] = False

# To use for loading in matched cut and vizualizing / subsequent analysis
settings_dict_matched = settings_dict
settings_dict_matched['useMatchedCut'] = True

In [6]:
# Run unit matching on non-matched study, will save new matched cut file (around 2 mins runtime per 2 sesssions compared)
unmatched_study = run_unit_matcher([data_dir], settings_dict_unmatched)
print('COMPLETED UNIT MATCHING')

Animal ID set
Animal ID set
Animal ID set
Animal ID set
9 9 [1 2 3 4 5 6 7 8 9] 10
Session data added, spikes sorted by cell
10 10 [ 1  2  3  4  5  6  7  8  9 10] 11
Session data added, spikes sorted by cell
10 10 [ 1  2  3  4  5  6  7  8  9 10] 11
Session data added, spikes sorted by cell
10 10 [ 1  2  3  4  5  6  7  8  9 10] 11
Session data added, spikes sorted by cell


c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\Envs\envPRISM\lib\site-packages\numpy\core\fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\Envs\envPRISM\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


Session1 - Cell 0; Session2 - Cell 0
M (1213, 23)
Session1 - Cell 0; Session2 - Cell 1
M (664, 23)
Session1 - Cell 0; Session2 - Cell 2
M (1112, 23)
Session1 - Cell 0; Session2 - Cell 3
M (788, 23)
Session1 - Cell 0; Session2 - Cell 4
M (758, 23)
Session1 - Cell 0; Session2 - Cell 5
M (537, 23)
Session1 - Cell 0; Session2 - Cell 6
M (169, 23)
Session1 - Cell 0; Session2 - Cell 7
M (624, 23)
Session1 - Cell 0; Session2 - Cell 8
M (2272, 23)
Session1 - Cell 0; Session2 - Cell 9
M (594, 23)
Session1 - Cell 1; Session2 - Cell 0
M (1213, 23)
Session1 - Cell 1; Session2 - Cell 1
M (664, 23)
Session1 - Cell 1; Session2 - Cell 2
M (1112, 23)
Session1 - Cell 1; Session2 - Cell 3
M (788, 23)
Session1 - Cell 1; Session2 - Cell 4
M (758, 23)
Session1 - Cell 1; Session2 - Cell 5
M (537, 23)
Session1 - Cell 1; Session2 - Cell 6
M (169, 23)
Session1 - Cell 1; Session2 - Cell 7
M (624, 23)
Session1 - Cell 1; Session2 - Cell 8
M (2272, 23)
Session1 - Cell 1; Session2 - Cell 9
M (594, 23)
Session1 - Cel

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\Envs\envPRISM\lib\site-packages\numpy\core\fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\Envs\envPRISM\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


Session1 - Cell 0; Session2 - Cell 0
M (9153, 23)
Session1 - Cell 0; Session2 - Cell 1
M (1720, 23)
Session1 - Cell 0; Session2 - Cell 2
M (1801, 23)
Session1 - Cell 0; Session2 - Cell 3
M (694, 23)
Session1 - Cell 0; Session2 - Cell 4
M (5553, 23)
Session1 - Cell 0; Session2 - Cell 5
M (302, 23)
Session1 - Cell 0; Session2 - Cell 6
M (113, 23)
Session1 - Cell 0; Session2 - Cell 7
M (946, 23)
Session1 - Cell 0; Session2 - Cell 8
M (5814, 23)
Session1 - Cell 0; Session2 - Cell 9
M (1784, 23)
Session1 - Cell 1; Session2 - Cell 0
M (9153, 23)
Session1 - Cell 1; Session2 - Cell 1
M (1720, 23)
Session1 - Cell 1; Session2 - Cell 2
M (1801, 23)
Session1 - Cell 1; Session2 - Cell 3
M (694, 23)
Session1 - Cell 1; Session2 - Cell 4
M (5553, 23)
Session1 - Cell 1; Session2 - Cell 5
M (302, 23)
Session1 - Cell 1; Session2 - Cell 6
M (113, 23)
Session1 - Cell 1; Session2 - Cell 7
M (946, 23)
Session1 - Cell 1; Session2 - Cell 8
M (5814, 23)
Session1 - Cell 1; Session2 - Cell 9
M (1784, 23)
Session1

c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\Envs\envPRISM\lib\site-packages\numpy\core\fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\aaoun\OneDrive - cumc.columbia.edu\Desktop\HussainiLab\Envs\envPRISM\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


Session1 - Cell 0; Session2 - Cell 0
M (5106, 23)
Session1 - Cell 0; Session2 - Cell 1
M (3567, 23)
Session1 - Cell 0; Session2 - Cell 2
M (1117, 23)
Session1 - Cell 0; Session2 - Cell 3
M (1289, 23)
Session1 - Cell 0; Session2 - Cell 4
M (418, 23)
Session1 - Cell 0; Session2 - Cell 5
M (149, 23)
Session1 - Cell 0; Session2 - Cell 6
M (516, 23)
Session1 - Cell 0; Session2 - Cell 7
M (5318, 23)
Session1 - Cell 0; Session2 - Cell 8
M (7271, 23)
Session1 - Cell 0; Session2 - Cell 9
M (1371, 23)
Session1 - Cell 1; Session2 - Cell 0
M (5106, 23)
Session1 - Cell 1; Session2 - Cell 1
M (3567, 23)
Session1 - Cell 1; Session2 - Cell 2
M (1117, 23)
Session1 - Cell 1; Session2 - Cell 3
M (1289, 23)
Session1 - Cell 1; Session2 - Cell 4
M (418, 23)
Session1 - Cell 1; Session2 - Cell 5
M (149, 23)
Session1 - Cell 1; Session2 - Cell 6
M (516, 23)
Session1 - Cell 1; Session2 - Cell 7
M (5318, 23)
Session1 - Cell 1; Session2 - Cell 8
M (7271, 23)
Session1 - Cell 1; Session2 - Cell 9
M (1371, 23)
Sessio

In [7]:
for ses in unmatched_study.sessions:
    print(ses.session_metadata.file_paths)
    print(ses.datetime)

{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\single_sequential/animal2/1-13_20210621-34-50x50cm-1500um-Test1_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\single_sequential/animal2/1-13_20210621-34-50x50cm-1500um-Test1.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\single_sequential/animal2/1-13_20210621-34-50x50cm-1500um-Test1.pos', 'ppm': 511}
2021-06-21 12:12:45
{'cut': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\single_sequential/animal2/1-13_20210621-34-50x50cm-1500um-Test2_3.cut', 'tet': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\single_sequential/animal2/1-13_20210621-34-50x50cm-1500um-Test2.3', 'pos': 'c:\\Users\\aaoun\\OneDrive - cumc.columbia.edu\\Desktop\\HussainiLab\\neuroscikit_test_data\\single_seq

In [ ]:
matched_study = make_study([data_dir], settings_dict_matched)
matched_study.make_animals()

In [19]:
for animal in matched_study.animals:
    print('New Animal')
    for session in animal.sessions.values():
        print('Session date & time: ' + str(session.datetime))
        print('Matched cell ids: ' + str(np.unique(session.get_spike_data()['spike_cluster'].cluster_labels)))

New Animal
2021-06-21 12:12:45
[1 2 3 4 5 6 7 8 9]
2021-06-21 15:58:32
[1 2 3 4 5 6 7 8 9]
2021-06-22 11:12:45
[ 1  2  3  4  5  6  7  8  9 10]
2021-06-22 16:15:30
[ 1  2  3  4  5  6  7  8  9 10]
